export const ACTION_MODE = {
  MOUSE: "MOUSE",
  RECT: "RECT",
  TEXT: "TEXT",
  IMAGE: "IMAGE",
  IFRAME: "IFRAME",
  LINE: "LINE",
  TRIANGLE: "TRIANGLE",
  CIRCLE: "CIRCLE",
  RHOMBUS: "RHOMBUS",
  HAND: "HAND",
} as const;

export const ACTION_TYPE = {
  DEFAULT: "DEFAULT",
  SELECT: "SELECT",
  BOTH_SELECT: "BOTH_SELECT",
} as const;
