export const EVENT = {
  ATTRIBUTE: {
    INIT_POSITION_KEY: "SYMBOL_INIT_POSITION_KEY",
    INIT_POSITION_VALUE_LEFT: "SYMBOL_INIT_POSITION_VALUE_LEFT",
    INIT_POSITION_VALUE_TOP: "SYMBOL_INIT_POSITION_VALUE_LEFT",
    INIT_POSITION_VALUE_WIDTH: "SYMBOL_INIT_POSITION_VALUE_WIDTH",
    INIT_POSITION_VALUE_HEIGHT: "SYMBOL_INIT_POSITION_VALUE_HEIGHT",
    ACT_POSITION_VALUE_LEFT: "SYMBOL_ACT_POSITION_VALUE_LEFT",
    ACT_POSITION_VALUE_TOP: "SYMBOL_ACT_POSITION_VALUE_TOP",
  },
} as const;
