export const EVENT = {
  RESIZE: {
    ATTRIBUTE: {
      INIT_POSITION_KEY: "RESIZE_INIT_POSITION_KEY",
      INIT_POSITION_VALUE_LEFT: "RESIZE_INIT_POSITION_VALUE_LEFT",
      INIT_POSITION_VALUE_TOP: "RESIZE_INIT_POSITION_VALUE_LEFT",
      INIT_POSITION_VALUE_WIDTH: "RESIZE_INIT_POSITION_VALUE_WIDTH",
      INIT_POSITION_VALUE_HEIGHT: "RESIZE_INIT_POSITION_VALUE_HEIGHT",
      ACT_POSITION_VALUE_LEFT: "RESIZE_ACT_POSITION_VALUE_LEFT",
      ACT_POSITION_VALUE_TOP: "RESIZE_ACT_POSITION_VALUE_TOP",
    },
  },
  DRAG: {
    ATTRIBUTE: {
      INIT_POSITION_KEY: "DRAG_INIT_POSITION_KEY",
      INIT_POSITION_VALUE_LEFT: "DRAG_INIT_POSITION_VALUE_LEFT",
      INIT_POSITION_VALUE_TOP: "DRAG_INIT_POSITION_VALUE_LEFT",
      INIT_POSITION_VALUE_WIDTH: "DRAG_INIT_POSITION_VALUE_WIDTH",
      INIT_POSITION_VALUE_HEIGHT: "DRAG_INIT_POSITION_VALUE_HEIGHT",
      ACT_POSITION_VALUE_LEFT: "DRAG_ACT_POSITION_VALUE_LEFT",
      ACT_POSITION_VALUE_TOP: "DRAG_ACT_POSITION_VALUE_TOP",
    },
  },
} as const;
