export const NODE = {
  ROLE: {
    GROUP_MASTER_KEY: "NODE_ROLE_GROUP_KEY",
    GROUP_SOLVE_CONTAINER_KEY: "NODE_ROLE_GROUP_SOLVE_CONTAINER_KEY",
    GROUP_SOLVE_ANCHOR_KEY: "NODE_ROLE_GROUP_SOLVE_ANCHOR_KEY",
  },
};
