export const PERMISSION_HANDLER = {
  RESIZABLE: 0b1,

  DRAGGABLE: 0b10,

  ROTATABLE: 0b100,
} as const;

export const PERMISSION_ROLE = {
  REMOVABLE: 0b1,

  CLONEABLE: 0b10,
} as const;

export const PERMISSION_ATTRIBUTE = {
  DATA_ELEMENT_ATTRIBUTE_KEY: "DATA_ELEMENT_ATTRIBUTE_KEY",
} as const;

export const NODE_HANDLER_ATTRIBUTE = {
  NODE_HANDLER_ATTRIBUTE_ROLE_KEY: "NODE_HANDLER_ATTRIBUTE_ROLE_KEY",
  NODE_HANDLER_ATTRIBUTE_CONTAINER: "NODE_HANDLER_ATTRIBUTE_CONTAINER",
} as const;
