export const PERMISSION_HANDLER = {
  RESIZABLE: 0b1,

  DRAGGABLE: 0b10,

  ROTATABLE: 0b100,
} as const;

export const PERMISSION_ROLE = {
  REMOVABLE: 0b1,

  CLONEABLE: 0b10,
} as const;

export const PERMISSION_ATTRIBUTE = {
  DATA_ELEMENT_ATTRIBUTE_KEY: "DATA_ELEMENT_ATTRIBUTE_KEY",
} as const;

export const NODE_HANDLER_ATTRIBUTE = {
  NODE_HANDLER_ATTRIBUTE_ROLE_KEY: "NODE_HANDLER_ATTRIBUTE_ROLE_KEY",
  NODE_HANDLER_ATTRIBUTE_CONTAINER: "NODE_HANDLER_ATTRIBUTE_CONTAINER",
} as const;

export const EVENT = {
  ATTRIBUTE: {
    INIT_POSITION_KEY: "SYMBOL_INIT_POSITION_KEY_TAG",
    INIT_POSITION_VALUE_LEFT: "SYMBOL_INIT_POSITION_VALUE_LEFT_TAG",
    INIT_POSITION_VALUE_TOP: "SYMBOL_INIT_POSITION_VALUE_TOP_TAG",
    INIT_POSITION_VALUE_WIDTH: "SYMBOL_INIT_POSITION_VALUE_WIDTH_TAG",
    INIT_POSITION_VALUE_HEIGHT: "SYMBOL_INIT_POSITION_VALUE_HEIGHT_TAG",
    ACT_POSITION_VALUE_LEFT: "SYMBOL_ACT_POSITION_VALUE_LEFT_TAG",
    ACT_POSITION_VALUE_TOP: "SYMBOL_ACT_POSITION_VALUE_TOP_TAG",

    RECT_LEFT: "SYMBOL_EVENT_ATTRIBUTE_RECT_LEFT",
    RECT_TOP: "SYMBOL_EVENT_ATTRIBUTE_RECT_TOP",
    RECT_WIDTH: "SYMBOL_EVENT_ATTRIBUTE_RECT_WIDTH",
    RECT_HEIGHT: "SYMBOL_EVENT_ATTRIBUTE_RECT_HEIGHT",
  },
} as const;

export const NODE = {
  ROLE: {
    GROUP_MASTER_KEY: "NODE_ROLE_GROUP_KEY",
    GROUP_SOLVE_CONTAINER_KEY: "NODE_ROLE_GROUP_SOLVE_CONTAINER_KEY",
    GROUP_SOLVE_ANCHOR_KEY: "NODE_ROLE_GROUP_SOLVE_ANCHOR_KEY",
  },
};
